# In this notebook we will demo Pandas python library

## Setup

## Import json and pandas lib

In [2]:
import json as js
import pandas as pd

## Load ads activity
#### Load the ads json data into jupyter notebook

In [3]:
path = r"/Users/srmore/Downloads/instagram-moresandeep-2025-08-25-5n1mOh2n/ads_information/instagram_ads_and_businesses/advertisers_using_your_activity_or_information.json"

In [4]:
with open(path) as op:
    data = js.load(op)

### Load FB Data

In [5]:
path_fb = r"/Users/srmore/Downloads/facebook-moresandeep-2025-08-25-herClN52/ads_information/advertisers_using_your_activity_or_information.json"

In [6]:
with open(path_fb) as op:
    data_fb = js.load(op)

## Describe data

#### List keys

In [7]:
data.keys()

dict_keys(['ig_custom_audiences_all_types'])

In [8]:
data_fb.keys()

dict_keys(['media', 'label_values', 'fbid'])

- What type of data?

In [10]:
type(data['ig_custom_audiences_all_types'])

list

In [12]:
type(data_fb['label_values'])

list

## Check how many records in our json object

In [13]:
len(data['ig_custom_audiences_all_types'])

1191

In [15]:
len(data_fb['label_values'][0]['vec'])

1191

### Let us look at first record

In [18]:
data['ig_custom_audiences_all_types'][0]

{'advertiser_name': 'Oracle Data Cloud',
 'has_data_file_custom_audience': True,
 'has_remarketing_custom_audience': False,
 'has_in_person_store_visit': False}

In [19]:
data_fb['label_values'][0]['vec'][0]

{'value': 'Oracle Data Cloud'}

In [20]:
type(data_fb['label_values'][0]['vec'][0])

dict

In [22]:
(data_fb['label_values'][0]['vec'][0]).keys()

dict_keys(['value'])

In [23]:
(data['ig_custom_audiences_all_types'])[0].keys()

dict_keys(['advertiser_name', 'has_data_file_custom_audience', 'has_remarketing_custom_audience', 'has_in_person_store_visit'])

# Using Pandas Library

In [25]:
ads_df = pd.DataFrame(data['ig_custom_audiences_all_types'])

In [27]:
ads_df_fb = pd.DataFrame(data_fb['label_values'][0]['vec'])

### List first 5 records (IG)

In [28]:
ads_df.head(5)

,advertiser_name,has_data_file_custom_audience,has_remarketing_custom_audience,has_in_person_store_visit
0,Oracle Data Cloud,True,False,False
1,American Home Shield,True,False,False
2,Netbhet,True,False,False
3,Zoom,True,False,False
4,Paytient App,True,False,False

In [29]:
ads_df_fb.head(2)

               value
0  Oracle Data Cloud
1           LiveRamp

In [33]:
ads_df.tail(3)

,advertiser_name,has_data_file_custom_audience,has_remarketing_custom_audience,has_in_person_store_visit
1188,Get up Earlier - Personal Training & Nutrition...,True,False,False
1189,GoDaddy,True,False,False
1190,Wavemaker Client Solutions,True,False,False

In [31]:
ads_df_fb.tail(2)

                           value
1189                    Thrivent
1190  Wavemaker Client Solutions

### Shape of my data

In [35]:
type(ads_df)

pandas.core.frame.DataFrame